services:
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile # target: runner
        container_name: app
        ports:
            - '3000:3000'
        networks:
            - mynet
        dns_opt:
            - edns0
            - trust-ad
            - ndots:1

    nginx:
        build:
            context: ./nginx
            dockerfile: ./Dockerfile
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/letsencrypt/:/etc/letsencrypt/
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/certbot-auth/:/opt/certbot-auth/
            - ./nginx/bin/:/opt/bin/
        networks:
            - mynet

networks:
    mynet:
        driver: bridge
